### ISSUE TITLE
Edge/Vertex overlap Heuristic

### ISSUE THREAD

**Issue by irapha** [gtagency/graph-reduction#4]
Honestly, I know that I mentioned that adding an "evenly distribute nodes" heuristic would be interesting, but i really like the results of my last tests (with the added "overlapping points" and "shrink to ten"). I am still seeing a lot of vertices overlapping with edges, so I wonder if we could have a heuristic for that.

**Comment by robert-lawrence** [comment]
This could be implemented as a addition to the overlapping points test, rather than a new test by itself. I'll tinker with the code tomorrow or tonight and see if there's an easy way to do it.

**Comment by irapha** [comment]
If you make this heuristic a part of overlapping points, bump up the score modifier (or at least tinker with it a bit to see what works best). I like the modifiers you have right now, btw

**Comment by robert-lawrence** [comment]
Fixed with SHA: 525501deedb824ad2b1a25eb36cdd9d87dd48416

**Comment by irapha** [comment]
Seems to work for a lot of test cases, but it's still not working for matrix4. I have no idea why honestly.

**Comment by irapha** [comment]
Also screwed up matrix8. It used to look like a neat little 3d box. Now it seems that it is _tending_ towards overlapping edges and vertices, as well as vertices and vertices.

**Comment by irapha** [comment]
Also not working for the newly created matrix12.

**Comment by robert-lawrence** [comment]
hmm. I'll look at it again

**Comment by robert-lawrence** [comment]
This is weird. It's only acting weird for me on matrix4. Matrix8 and matrix12 work fine.

**Comment by irapha** [comment]
Ok, no. It seems like it's working but, for instance. Matrix 12 is not supposed to look like this:
![screen shot 2015-02-20 at 18 39 50](https://cloud.githubusercontent.com/assets/7386247/6311378/ed7f5e60-b92f-11e4-92bf-e286ade2bf8c.png)
but it should look like this:
![screen shot 2015-02-20 at 18 38 13](https://cloud.githubusercontent.com/assets/7386247/6311379/ed7ff6f4-b92f-11e4-9259-7629df679e86.png)

For matrix8, it should not look like this:

![screen shot 2015-02-20 at 18 41 41](https://cloud.githubusercontent.com/assets/7386247/6311408/42981770-b930-11e4-8f3a-a6df043dd33a.png)
but rather like one of these:
![screen shot 2015-02-20 at 18 42 10](https://cloud.githubusercontent.com/assets/7386247/6311407/42940b62-b930-11e4-8211-f23520bc2c14.png)

**Comment by robert-lawrence** [comment]
I almost had it fixed, but I ended up breaking the whole thing. This might take some more work and time than the other bugs.

**Comment by irapha** [comment]
I figured it would. I will work on it too, but I have a ton of HW this weekend and monday so I'll only be able to take a look at it on the next meeting. 

You can always revert changes, btw. Do you commit frequently? (Cuz I don't, so I'd be screwed, lol)

**Comment by robert-lawrence** [comment]
not that frequently :/ I'd have to undo most of my work... A good lesson to remember in the future. I'll see what I can do.

**Comment by robert-lawrence** [comment]
Almost finished! What's the 34 matrix supposed to look like again?

**Comment by irapha** [comment]
NICE. What ended up fixing it?

**Comment by robert-lawrence** [comment]
I added another parameter to the score fn and I forgot to update all of the calls to it. Because it had a default value, I wouldn't get any errors but the scoring system would be messed up.

**Comment by robert-lawrence** [comment]
I think we're about ready to add a README and a friendlier interface so others can use it!

**Comment by irapha** [comment]
Don't worry. I'll work on that first thing tomorrow. You can start with the interface part. As long as the functionality doesn't change much, I can get the readme done by Wednesday. 

—
